### PR TITLE
Update binding.gyp

### PR DESCRIPTION
**Pull request by Kamil93**
Added support for FreeBSD

### CODE REVIEW

**Comment by goriunov** [comment]
That looks alright to me unfortunately i can not test that anytime soon. Have you tested if it works ?

**Comment by Kamil93** [comment]
Yes it works. This was the only Way to begin my adventure with cws ;)

**Comment by Kamil93** [comment]
I can't merge it, haven't write access

**Comment by goriunov** [comment]
Ohh i see :(

**Pull request merged**
